//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bbrz_projekt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRating
    {
        public byte[] RatingDate { get; set; }
        public Nullable<int> Rating { get; set; }
        public int FK_Game { get; set; }
        public string FK_User { get; set; }
    
        public virtual tblGame tblGame { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
